// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UYcRGfJKJywf5bIoyJ7-M2_0lwRsW6Q',
    appId: '1:577462310361:web:54845f0a8d73507524b5c8',
    messagingSenderId: '577462310361',
    projectId: 'lector-app-6c184',
    authDomain: 'lector-app-6c184.firebaseapp.com',
    storageBucket: 'lector-app-6c184.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6ppz6K3pUtqzOIiGaWVvea7JDVnJow4',
    appId: '1:577462310361:android:f2c24c492b0d28b724b5c8',
    messagingSenderId: '577462310361',
    projectId: 'lector-app-6c184',
    storageBucket: 'lector-app-6c184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8N4oOYE11SzZkzfQLpvn7EUUhkuhIKfo',
    appId: '1:577462310361:ios:32be4a46fd8792ac24b5c8',
    messagingSenderId: '577462310361',
    projectId: 'lector-app-6c184',
    storageBucket: 'lector-app-6c184.firebasestorage.app',
    iosBundleId: 'com.example.lector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8N4oOYE11SzZkzfQLpvn7EUUhkuhIKfo',
    appId: '1:577462310361:ios:32be4a46fd8792ac24b5c8',
    messagingSenderId: '577462310361',
    projectId: 'lector-app-6c184',
    storageBucket: 'lector-app-6c184.firebasestorage.app',
    iosBundleId: 'com.example.lector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5UYcRGfJKJywf5bIoyJ7-M2_0lwRsW6Q',
    appId: '1:577462310361:web:a928a5c42952be8724b5c8',
    messagingSenderId: '577462310361',
    projectId: 'lector-app-6c184',
    authDomain: 'lector-app-6c184.firebaseapp.com',
    storageBucket: 'lector-app-6c184.firebasestorage.app',
  );
}
